# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-23 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default=None, max_length=6, null=True)),
                ('rarity_low', models.IntegerField(default=None, null=True)),
                ('rarity_high', models.IntegerField(default=None, null=True)),
                ('hero_type', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('colorless', 'colorless')], default=None, max_length=16, null=True)),
                ('weapon_type', models.CharField(default=None, max_length=32, null=True)),
                ('move_type', models.CharField(default=None, max_length=16, null=True)),
                ('appears_in', models.CharField(default=None, max_length=128, null=True)),
                ('voice_actor', models.CharField(default=None, max_length=32, null=True)),
                ('art_by', models.CharField(default=None, max_length=32, null=True)),
                ('release_date', models.DateTimeField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('health', models.IntegerField(default=None, null=True)),
                ('attack', models.IntegerField(default=None, null=True)),
                ('speed', models.IntegerField(default=None, null=True)),
                ('defense', models.IntegerField(default=None, null=True)),
                ('resistance', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
