# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-23 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='img',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
