# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-20 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heros',
            name='appears_in',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='attack',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='defense',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='health',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='move_type',
            field=models.CharField(choices=[('infantry', 'infantry'), ('cavalry', 'cavalry'), ('armored', 'armored'), ('flying', 'flying')], default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='release_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='resistance',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='speed',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='type',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('colorless', 'colorless')], default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='heros',
            name='voice_actor',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='heros',
            name='weapon_type',
            field=models.CharField(choices=[('sword', 'sword'), ('lance', 'lance'), ('axe', 'axe'), ('red_bow', 'red_bow'), ('blue_bow', 'blue_bow'), ('green_bow', 'green_bow'), ('colorless_bow', 'colorless_bow'), ('red_tome', 'red_tome'), ('blue_tome', 'blue_tome'), ('green_tome', 'green_tome'), ('red_dragger', 'red_dragger'), ('blue_dragger', 'blue_dragger'), ('green_dragger', 'green_dragger'), ('colorless_dragger', 'colorless_dragger'), ('red_breath', 'red_breath'), ('blue_breath', 'blue_breath'), ('green_breath', 'green_breath'), ('colorless_breath', 'colorless_breath'), ('red_beast', 'red_beast'), ('blue_beast', 'blue_beast'), ('green_beast', 'green_beast'), ('colorless_beast', 'colorless_beast'), ('staff', 'staff')], default=None, max_length=32, null=True),
        ),
    ]
