# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-20 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0002_auto_20190520_0502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heros',
            new_name='Heroes',
        ),
    ]
