# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-25 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0003_auto_20190525_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pools',
            old_name='featured_units',
            new_name='heroes',
        ),
    ]
