# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-26 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0004_auto_20190525_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pools',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='pools',
            name='start_date',
        ),
        migrations.AddField(
            model_name='pools',
            name='image',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
