# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0005_auto_20190521_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='move_type',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='weapon_type',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
