# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0005_auto_20190526_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='pools',
            name='url_name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
